### ISSUE TITLE
Friendlier message about WordNet download

### ISSUE THREAD

**Issue by DavidMertz** [Chad-Mowbray/iamb-classifier#4]
If WordNet is not installed, an ugly traceback appears.  This could be caught, and display a message roughly like:

```
WordNet is not installed.  Run:

    python -c "import nltk; nltk.download('words')"

To remedy this
```

**Comment by Chad-Mowbray** [comment]
Thanks, I added an error message and also re-included the nltk wordnet files, so the error shouldn't be occurring now anyway.
